ls:
  .md: regex:README | regex:CONTRIBUTING | regex:LICENSE | snake_case
  .dir: snake_case|regex:.vscode
  .go: snake_case
  .sh: snake_case
  .sql: snake_case
  .sql.tpl: snake_case
  .vscode/*:
    .json: regex:settings|regex:launch:regex:extensions
  sample_dbs:
    .schema.dump.sql: snake_case
  db_object_kind/*:
    .dir: SCREAMING_SNAKE_CASE
  db_object_kind/*/*: # {KIND}/queries/
    .dir: snake_case
  db_object_kind/*/*/*/tests/*:
    .tsv: regex:results
    .yaml: regex:explain
ignore:
  - .git