name_template = "{{.kind}}_constraints_{{.oid}}{{.packed}}"

[oid]
  normalized = true
  denormalized = false
[packed]
  _packed = true
  "" = false
[kind]
  check = "c"
  primary_key = "p"
  foreign_key = "f"
  unique = "u"
  exclusion = "x"
  all = ""
