name_template = "{{.oid}}_{{.kind}}{{.packed}}"

[oid]
  normalized = true
  denormalized = false
[packed]
  _packed = true
  "" = false
[kind] # should be equivalent to contype
  foreign_key_constraints = "f"
  constraints_filtered_by_kind = ":" # trigger, constraint, PK, unique, unique constraints all have the same columns
  constraints = ""
