name_template = """
{{- if (not .filter_on_partitioning) -}}all_{{- end -}}
foreign_tables_{{.oid}}{{ .filter_on_partitioning }}{{- .packed -}}
"""
[oid]
  normalized = true
  denormalized = false
[pg_class_category]
  kind = "FOREIGN TABLE"
[kind]
  always = 'f'
[filter_on_partitioning]
  "" = false
  _filtered_by_partitioning = true
[packed]
  "" = false
  _packed = true