SELECT
    col.attrelid AS rel_oid
  , rel.relname AS rel_name
  , col.attname AS col_name
  , col.atttypid AS type_oid -- zero if the column has been dropped
  , type_.typname AS type_name
  , ns.nspname AS type_schema
  , col.attstattarget AS stats_detail_level -- int4: for ANALYZE
  -- , col.attlen AS type_length_bytes
     -- int2:  a copy of pg_type.typlen, internal represenation byte length.
     -- -1 for variable lengths, -2 for a null-terminated c-string.
  , col.attnum AS col_number -- int2: 1-indexed
  , col.attndims AS dimension_number -- dimension_number > 0 means array
  , col.atttypmod AS type_length -- int4, for type-specific input and length-coersion, e.g. varchar(n)
  -- , (
  --     CASE WHEN col.atthasmissing THEN col.attmissingval ELSE NULL END
  --   ) AS missing_val -- anyarray nullable
  , (
      /* a 2-byte integer 00000098 76543210
                          -------- ~~~~~~---
                generation-^  identity--^  ^- nullability
        TODO: validation bitmask?
      */
      CAST(0 AS SMALLINT) -- int2
      | 1<<(CASE WHEN col.attnotnull THEN 1 ELSE 0 END)
      | 1<<(
            CASE col.attidentity
              WHEN ''  THEN 2 -- ''  => not an identity column
              WHEN 'a' THEN 3 -- 'a' => always generated
              WHEN 'd' THEN 4 -- 'd' => generated by default
              ELSE 0
            END
          )
      | 1<<(
            CASE col.attgenerated
              WHEN ''  THEN 8
              WHEN 's' THEN 9
              ELSE          10
            END
          )
    ) AS nullability_identity_generation
  , (
      CASE
        WHEN col.atthasdef THEN pg_catalog.pg_get_expr(col_def.adbin, col_def.adrelid)
        ELSE NULL
      END
   ) AS expr
    -- either generation, identity generation, or default expression OR just null.
  , col.attoptions AS col_options -- text[], 'key=value' strings
  , col.attfdwoptions AS fdw_options -- ^same
FROM pg_catalog.pg_attribute AS col -- https://www.postgresql.org/docs/current/catalog-pg-attribute.html
INNER JOIN pg_catalog.pg_class AS rel -- https://www.postgresql.org/docs/current/catalog-pg-class.html
  ON col.attrelid = rel.oid
INNER JOIN pg_catalog.pg_type AS type_ -- https://www.postgresql.org/docs/current/catalog-pg-type.html
  ON col.attnum > 0 -- system columns have negative `attnum`, ordinary have >=1
  AND col.atttypid > 0 -- un-dropped columns only
  AND col.atttypid = type_.oid
INNER JOIN pg_catalog.pg_namespace AS ns ON type_.typnamespace = ns.oid
LEFT JOIN pg_catalog.pg_attrdef AS col_def -- https://www.postgresql.org/docs/current/catalog-pg-attrdef.html
  ON col.atthasdef
  AND col.attrelid = col_def.adrelid
  AND col.attnum = col_def.adnum