name_template = """
{{- if (not .filter_on_persistence) -}}all_{{- end -}}
sequences_{{- .oid -}}{{- .packed }}{{- .filter_on_persistence -}}
"""
[oid]
  normalized = true
  denormalized = false
[pg_class_category]
  kind = "SEQUENCE"
[kind]
  always = 'S'
[filter_on_persistence]
  "" = false
  _filtered_by_persistence = true
[packed]
  "" = false
  _packed = true