name_template = """
{{- $filter_on_persistence := eq .filter_on_persistence "one" -}}

{{- if (not $filter_on_persistence) -}}all_{{- end -}}
sequences
{{- .packed }}
{{- if $filter_on_persistence -}}_filtered_by_persistence{{- end -}}
"""
[pg_class_category]
  kind = "SEQUENCE"
[kind]
  always = 'S'
[filter_on_persistence]
  all = false
  one = true
[packed]
  "" = false
  _packed = true