SELECT
  col.attrelid AS relation_oid
  , col.attname AS col_name
  , col.attnum AS col_number -- int2: 1-indexed
  , col.atttypid AS type_oid -- can be 0
  , col.attstattarget AS stats_detail_level -- int4: for ANALYZE
  -- , col.attlen AS type_length_bytes
     -- int2:  a copy of pg_type.typlen, internal represenation byte length.
     -- -1 for variable lengths, -2 for a null-terminated c-string.
  , col.attndims AS dimension_number -- dimension_number > 0 means array
  , col.atttypmod AS type_length -- int4, for type-specific input and length-coersion, e.g. varchar(n)
  -- , (
  --     CASE WHEN col.atthasmissing THEN col.attmissingval ELSE NULL END
  --   ) AS missing_val -- anyarray nullable
  , col.attnotnull AS not_null -- bool NOTE: all not-null constraints represented here, NOT in pg_constraint
  , col.attidentity AS column_identity
    -- '' => not an identity column
    -- 'a' => always generated
    -- 'd' => generated by default
  , col.attgenerated AS col_generated
    -- '' => not generated
    -- 's' => stored
  , (
      CASE
        WHEN col.atthasdef THEN pg_catalog.pg_get_expr(col_def.adbin, col_def.adrelid)
        ELSE NULL
      END
   ) AS expr
    -- either generation, identity generation, or default expression OR just null.
  , col.attoptions AS col_options -- text[], 'key=value' strings
  , col.attfdwoptions AS fdw_options -- ^same
  , pg_catalog.col_description(col.attrelid, col.attnum) AS col_comment
FROM pg_catalog.pg_attribute AS col -- https://www.postgresql.org/docs/current/catalog-pg-attribute.html
LEFT JOIN pg_catalog.pg_attrdef AS col_def -- https://www.postgresql.org/docs/current/catalog-pg-attrdef.html
  ON col.atthasdef
  AND col.attrelid = col_def.adrelid
  AND col.attnum = col_def.adnum