name_template = """
{{- $any_filters := or
      .filter_on_partitioning
      .filter_on_persistence
      .filter_on_kind
-}}
{{- if not $any_filters -}}all_{{- end -}}
indices_{{.oid}}
{{- if $any_filters -}}_filtered_by{{- end -}}
{{- .filter_on_partitioning -}}
{{- .filter_on_persistence -}}
{{- .filter_on_kind -}}
{{-  .packed -}}
"""
[oid]
  normalized = true
  denormalized = false
[pg_class_category]
  kind = "INDEX"
[filter_on_partitioning]
  "" = false
  _partitioning = true
[filter_on_persistence]
  "" = false
  _persistence = true
[filter_on_kind]
  "" = false
  _kind = true
[packed]
  "" = false
  _packed = true