name_template = "{{.internal}}_languages_{{.oid}}"
[oid]
  normalized = true
  denormalized = false
[internal]
  internal = "only"
  all = "include"
  # external = "exclude" # to fetch external languages only, filter with `where lanispl`
